STAR_WARS_BASE = '/questionnaire/0/star_wars/789/'
STAR_WARS_INTRODUCTION = STAR_WARS_BASE + 'star-wars/0/introduction'
STAR_WARS_TRIVIA_PART_1 = STAR_WARS_BASE + 'star-wars/0/star-wars-trivia'
STAR_WARS_TRIVIA_PART_2 = STAR_WARS_BASE + 'star-wars/0/star-wars-trivia-part-2'
STAR_WARS_TRIVIA_PART_3 = STAR_WARS_BASE + 'star-wars/0/star-wars-trivia-part-3'
STAR_WARS_SUMMARY = STAR_WARS_BASE + 'star-wars/0/summary'
STAR_WARS_SUMMARY_REGEX = STAR_WARS_BASE + 'star-wars/0/summary$'
STAR_WARS_SUBMIT = STAR_WARS_BASE + 'submit-answers'

ROGUE_ONE_INTRODUCTION = '/questionnaire/0/rogue_one/789/rogue-one/0/introduction'
