coverage:
  status:
    project:
      default:
        target: 100%
        threshold: null
        base: auto
    patch:
      default: on
    changes:
      default: off
codecov:
  branch: v3
comment: false
