version: '3'

services:

  datastore:
    image: knarz/datastore-emulator
    ports:
      - "8432:8432"

  redis:
    image: redis:4
    ports:
      - "6379:6379"

  go-launch-a-survey:
    image: onsdigital/go-launch-a-survey:latest
    environment:
      SURVEY_RUNNER_URL: http://localhost:5000
      SURVEY_RUNNER_SCHEMA_URL: http://docker.for.mac.host.internal:5000
    restart: always
    ports:
      - "8000:8000"
