MUTUALLY_EXCLUSIVE_BASE = '/questionnaire/test/mutually_exclusive/789/'

MUTUALLY_EXCLUSIVE_DAY_MONTH_YEAR_DATE = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-date-group/0/mutually-exclusive-date'
MUTUALLY_EXCLUSIVE_CURRENCY = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-currency-group/0/mutually-exclusive-currency'
MUTUALLY_EXCLUSIVE_NUMBER = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-number-group/0/mutually-exclusive-number'
MUTUALLY_EXCLUSIVE_PERCENTAGE = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-percentage-group/0/mutually-exclusive-percentage'
MUTUALLY_EXCLUSIVE_TEXTFIELD = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-textfield-group/0/mutually-exclusive-textfield'
MUTUALLY_EXCLUSIVE_MONTH_YEAR_DATE = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-month-year-date-group/0/mutually-exclusive-month-year-date'
MUTUALLY_EXCLUSIVE_YEAR_DATE = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-year-date-group/0/mutually-exclusive-year-date'
MUTUALLY_EXCLUSIVE_UNIT = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-unit-group/0/mutually-exclusive-unit'
MUTUALLY_EXCLUSIVE_DROPDOWN = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-dropdown-group/0/mutually-exclusive-dropdown'
MUTUALLY_EXCLUSIVE_DURATION = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-duration-group/0/mutually-exclusive-duration'
MUTUALLY_EXCLUSIVE_TEXTAREA = MUTUALLY_EXCLUSIVE_BASE + 'mutually-exclusive-textarea-group/0/mutually-exclusive-textarea'
