# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: eu.gcr.io/census-eq-ci/eq-survey-runner
  tag: latest
  pullPolicy: Always

submissionBucket: ""
googleTagManagerId: ""
googleTagManagerAuth: ""
googleTagManagerPreview: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true

resources:
  requests:
    cpu: "3"

autoscaler:
    minReplicas: 3
    maxReplicas: 96
    targetCPUUtilizationPercentage: 50
