name: EQ merge into master

on: [pull_request]

jobs:
    build_and_push_Docker_image:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.x]
                python-version: [3.7.x]

        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install apt dependencies
              run: sudo apt-get install libsnappy-dev
            - name: Install Pip dependencies
              run: pip install -U pip pipenv==2018.5.18 wheel
            - name: Set up Pipenv
              run: pipenv install --dev --deploy
            - name: Compile application
              run: yarn compile
            - name: Populate application version
              run: printf $(git rev-parse HEAD) > .application-version
            - name: Boot up EQ
              run: docker-compose up --build -d
            - name: Run unit tests
              run: ./scripts/run_tests_functional.sh