name: EQ functional tests

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [6.x]
                python:
                  - 3.7.x
                  - 2.x

        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install python version
              uses: gabrielfalcao/pyenv-action@v5
              with:
                default: "${{ matrix.python }}"
                command: pip install -U pip
            - name: List installed python versions
              run: pyenv versions

