name: EQ functional tests

on: [pull_request]

jobs:
    functional_tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [6.x]

        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Compile application
              run: yarn compile
            - name: Populate application version
              run: printf $(git rev-parse HEAD) > .application-version
            - name: Boot up EQ
              run: docker-compose up --build -d
            - name: Run unit tests
              run: ./scripts/run_tests_functional.sh
