name: EQ merge into master

on:
    push:
        branches:
            - master

jobs:
    build_and_push_Docker_image:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.x]

        steps:
            - uses: actions/checkout@v2
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Node dependencies
              run: yarn
            - name: Populate application version
              run: printf $(git rev-parse HEAD) > .application-version
            - name: Compile application
              run: yarn compile
            - name: Build onsdigital/eq-survey-runner Docker image
              run: docker build -t onsdigital/eq-survey-runner:$TAG -f Dockerfile .
              env:
                  TAG: latest
            - name: Build onsdigital/eq-survey-runner-static Docker image
              run: docker build -t onsdigital/eq-survey-runner-static:$TAG -f Dockerfile.static .
              env:
                  TAG: latest
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Push to onsdigital/eq-survey-runner
              run: docker push onsdigital/eq-survey-runner:$TAG
              env:
                  TAG: latest
            - name: Push to onsdigital/eq-survey-runner-static
              run: docker push onsdigital/eq-survey-runner-static:$TAG
              env:
                  TAG: latest
